USER_NAME_MIN_LENGTH = 3
USER_NAME_MAX_LENGTH = 50
USER_SURNAME_MIN_LENGTH = 3
USER_SURNAME_MAX_LENGTH = 50
USER_DATE_OF_BIRTH_MIN_LENGTH = 8
USER_DESCRIPTION_MAX_LENGTH = 1000
USER_EMAIL_MAX_LENGTH = 200
PHONE_NUMBER_MIN_LENGTH = 10
PHONE_NUMBER_MAX_LENGTH = 15


